config/routes.rb
Rails.application.routes.draw do

  get 'chats/index' => 'chats#index'

  ActiveAdmin.routes(self)
  get 'about/show' => 'about#show'

  resources :orders

  resources :dishes

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'dishes#index'

end

app/models/dish.rb
class Dish < ActiveRecord::Base
  belongs_to :user

  has_many :ingredients
  has_many :portions
  has_many :orders, through: :portions

  has_attached_file :picture,
    styles: { large: "800x800>", medium: "300x300>", thumb: "100x100>" }

  validates :name, presence: true

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  LIST = ['fraise', 'pomme']
  belongs_to :dish
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order
end

app/models/portion.rb
class Portion < ActiveRecord::Base
  belongs_to :dish
  belongs_to :order
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :dishes
  has_many :portions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.picture = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [ :show, :edit, :update, :destroy]

  def index
    @dishes = Dish.all
    # @dish1= Dish.find(1)
    # @dish2= Dish.find(2)
    # @dish3= Dish.find(3)
  end

  def show
    @ingredient = Ingredient.new
  end

  def new
    # NEXT WEEK
    @dish = Dish.new
    @ingredient = Ingredient.new
  end

  def create
    @dish = Dish.new(dish_params)
    @dish.user_id = current_user.id
    if @dish.save
    @ingredient = Ingredient.new(name: ingredient_params[:name], dish_id: Dish.last.id)
    @ingredient.save
      redirect_to dish_path(@dish)
    else
      redirect_to new_dish_path(@dish)
    end
  end

  def edit
    # NEXT WEEK
    @dish = Dish.find(params[:id])
  end

  def update
    # NEXT WEEK
  end

  def destroy
    # NEXT WEEK
  end

  private
  def set_dish
  @dish = Dish.find(params[:id])
  end

  def dish_params
    params.require(:dish).permit(:name, :description, :price_per_portion, :picture)
    # :user_id current_user
  end

  def ingredient_params
    params[:dish].require(:ingredient).permit(:name)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [ :show, :edit, :update, :destroy]
  def index
    @orders = Order.all
    # @order1= order.find(1)
    # @order2= order.find(2)
    # @order3= order.find(3)
  end

  def show

    @ingredient = Ingredient.new
  end

  def new
    # NEXT WEEK
    @order = Order.new
    @ingredient = Ingredient.new
  end

  def create
    @order = Order.new(order_params)
    @order.save
  end

  def edit
    # NEXT WEEK
    @order = Order.find(params[:id])
  end

  def update
    # NEXT WEEK
  end

  def destroy
    # NEXT WEEK
  end


  private
  def set_order
  @order = order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:name, :description, :price_per_portion)
    # :user_id current_user
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @dishes = Dish.all
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/about/show.html.erb
<h1 class="text-center">À propos</h1>
<br>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
<h4>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque sed illo officia placeat vero, praesentium! Magni nihil unde, ipsum molestias consequuntur esse, qui harum. Obcaecati reprehenderit veritatis neque, fugit provident?</h4>
    </div>
  </div>
</div>

app/views/chats/index.html.erb
<h1 class="text-center">Cité-U Tchat</h1>
<div class="container">
  <div class="row">
    <div class=" col-md-1"></div>
    <div class=" col-md-10" id="chatwee-widget"></div>
  </div>
</div>


<script src="http://repository.chatwee.com/scripts/35925349ec1d09383d04820fc4210063.js" type="text/javascript" charset="UTF-8"></script>

app/views/dishes/create.html.erb
<h1>Dishes#create</h1>
<p>Find me in app/views/dishes/create.html.erb</p>

app/views/dishes/destroy.html.erb
<h1>Dishes#destroy</h1>
<p>Find me in app/views/dishes/destroy.html.erb</p>

app/views/dishes/edit.html.erb
<h1 class="text-center">Modifier votre plat</h1>

app/views/dishes/index.html.erb
<!--
<br>
<br>

<div class="container">
  <div class="row">
    <div class=" col-md-1"></div>
    <div class=" col-md-10" id="chatwee-widget"></div>
  </div>
</div> -->

<!--
<br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br><br> <br> <br> <br> -->
<!-- begin olark code -->
<script data-cfasync="false" type='text/javascript'>/*<![CDATA[*/window.olark||(function(c){var f=window,d=document,l=f.location.protocol=="https:"?"https:":"http:",z=c.name,r="load";var nt=function(){
f[z]=function(){
(a.s=a.s||[]).push(arguments)};var a=f[z]._={
},q=c.methods.length;while(q--){(function(n){f[z][n]=function(){
f[z]("call",n,arguments)}})(c.methods[q])}a.l=c.loader;a.i=nt;a.p={
0:+new Date};a.P=function(u){
a.p[u]=new Date-a.p[0]};function s(){
a.P(r);f[z](r)}f.addEventListener?f.addEventListener(r,s,false):f.attachEvent("on"+r,s);var ld=function(){function p(hd){
hd="head";return["<",hd,"></",hd,"><",i,' onl' + 'oad="var d=',g,";d.getElementsByTagName('head')[0].",j,"(d.",h,"('script')).",k,"='",l,"//",a.l,"'",'"',"></",i,">"].join("")}var i="body",m=d[i];if(!m){
return setTimeout(ld,100)}a.P(1);var j="appendChild",h="createElement",k="src",n=d[h]("div"),v=n[j](d[h](z)),b=d[h]("iframe"),g="document",e="domain",o;n.style.display="none";m.insertBefore(n,m.firstChild).id=z;b.frameBorder="0";b.id=z+"-loader";if(/MSIE[ ]+6/.test(navigator.userAgent)){
b.src="javascript:false"}b.allowTransparency="true";v[j](b);try{
b.contentWindow[g].open()}catch(w){
c[e]=d[e];o="javascript:var d="+g+".open();d.domain='"+d.domain+"';";b[k]=o+"void(0);"}try{
var t=b.contentWindow[g];t.write(p());t.close()}catch(x){
b[k]=o+'d.write("'+p().replace(/"/g,String.fromCharCode(92)+'"')+'");d.close();'}a.P(2)};ld()};nt()})({
loader: "static.olark.com/jsclient/loader0.js",name:"olark",methods:["configure","extend","declare","identify"]});
/* custom configuration goes here (www.olark.com/documentation) */
olark.identify('5687-759-10-4012');/*]]>*/</script><noscript><a href="https://www.olark.com/site/5687-759-10-4012/contact" title="Contact us" target="_blank">Questions? Feedback?</a> powered by <a href="http://www.olark.com?welcome" title="Olark live chat software">Olark live chat software</a></noscript>
<!-- end olark code -->

<!-- ****************************************
****************************************
****************************************
****************************************  *séparation olark
****************************************
****************************************
**************************************** -->

<h2 class="text-center">MENU DU JOUR</h2>
<br><br>
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-offset-3 col-xs-6 ">
      <% @dishes.each do |dish| %>
        <div class="row">
          <div class="col-md-10">

            <h3 class="yummmy"><%= link_to dish.name, dish_path(dish) %></h3>


            <p><%= dish.description %> <h3><%= dish.price_per_portion%> €</h3></p>
            <div class="caption text-center">





            </div>
          </div>
        </div>
<% end %>

<div id="footer">
      <div class="container">
        <div class="row">
          <div class="col-xs-6 col-sm-12">
            <ul class="list-inline social">
              <li>
                  <div class="col-xs-2">
       <%= link_to "http://facebook.com" do %>
       <%= image_tag "face_chalk.jpg", width:"75px", id: "logo" %>
       <% end %>
              </li>
              <li>
                 <div class="col-xs-2">
       <%= link_to "http://facebook.com" do %>
       <%= image_tag "twitt_chalk.jpg", width:"75px", id: "logo" %>
       <% end %>
              <li>
                <div class="col-xs-2">
       <%= link_to "http://facebook.com" do %>
       <%= image_tag "in_chalk.jpg", width:"75px", id: "logo" %>
       <% end %>
              </li>
              <li>
                <div class="col-xs-2">
       <%= link_to "http://facebook.com" do %>
       <%= image_tag "you_tube_chalk.jpg", width:"75px", id: "logo" %>
       <% end %>
              </li>
            </ul>
          </div>

        </div>
      </div>
    </div>

<p class="text-center"><%= link_to "À propos", about_show_path %></p>




   <!--  <%= Dish.first.picture %> -->

<!-- <script src="http://repository.chatwee.com/scripts/35925349ec1d09383d04820fc4210063.js" type="text/javascript" charset="UTF-8"></script> -->

<!-- *********************
*********************
*********************
*********************    *séparation entre menu de la semaine et des étudiants
*********************
*********************
*********************
********************* -->

app/views/dishes/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Proposer un plat</h1>
            <%= simple_form_for(@dish) do |f| %>
              <%= f.error_notification %>
              <%= f.input :name, label: 'Nom du plat', placeholder: "Envoyez du rêve !" %>
              <%= f.input :description, :as => :string, label: 'Description', placeholder: "Faites saliver...", input_html: { rows: "2" } %>
              <%= f.input :price_per_portion, label: 'Prix de la portion', placeholder: "€€€€€"%>
              <%= f.fields_for @ingredient do |p| %>
                <% p.input :name, label: "Ingrédients", as: :collection_select, collection: Ingredient.all.map { |i| i.name }.uniq %>
              <% end %>
<!--               <div class="text-center"> -->
                <%= f.button :submit, label: "Ajouter votre plat", class: "btn btn-primary" %>
<!--               </div> -->
      <% end %>
    </div>
  </div>
</div>

<br> <br>

app/views/dishes/show.html.erb
<div class="container text-center">
  <div class="container-fluid">
  <div class="row">
    <div class="col-xs-offset-3 col-xs-6 ">
  <h2><%= @dish.name%></h2>
  <p><%= @dish.description%></p>
      <h2>Ingrédients</h2>
      <p>
        <ul class="list-unstyled">
          <% @dish.ingredients.each do |ingredient|%>
            <li>
              <%= ingredient.name %>
            </li>
          <% end %>
        </ul>
      </p>
      <h1><%= link_to "Commander", new_order_path %></h1>


</div>


<div ><h2><%= @dish.price_per_portion %> €</h2></div>

app/views/dishes/show_0.html.erb
<div class="container padded">
  <div class="row">
    <div class="col-lg-6 col-sm-12">
      <div class="card-wrapper row-bg">
        <div class="card row-bg">
          <span class="card-description">
            <h2><%= @dish.name%></h2>
          </span>
          <span class="card-text">
            <p><%= @dish.description%></p>
            <h2>Ingrédients</h2>
            <p>
              <ul class="list-unstyled">
                <% @dish.ingredients.each do |ingredient|%>
                  <li>
                    <%= ingredient.name %>
                  </li>
                <% end %>
              </ul>
            </p>
          </span>
          <span class="card-user">
              <%= image_tag User.first.picture, class: "avatar avatar-big avatar-bordered"%>
          </span>
          <a href="#" class="card-link"></a>
        </div>
      </div>
    </div>

    <div class="col-lg-6 col-sm-12">
      <div class="card-wrapper row-bg">
        <div class="card row-bg">
          <span class="card-description text-center"></span>
          <span class="card-text">
            <%= image_tag @dish.picture.url(:large)%>
          </span>
          <span class="card-user">
            <p class="avatar avatar-bordered"><%= @dish.price_per_portion%> €</p>
          </span>
          <a href="#" class="card-link"></a>
        </div>
      </div>
    </div>
  </div>
</div>


     <!--  <div class="card-dish">
        <span class="card-user">
          <img src='user.picture' class="avatar avatar-bordered"/>
        </span>
        <span class="card-shadow"></span>
        <span class="card-description"><h2><%#= @dish.name%></h2></span>
        <span class="card-text">
          <p><%#= @dish.description%></p>
        </span>
        <span>
          <p>Liste des ingrédients</p> -->
          <!-- <ul class="list-unstyled"> -->
            <%# @dish.ingredients.each do |ingredient|%>
              <!-- <li>
                <%#= ingredient.name %>
              </li>
            <%# end %>
          </ul>
        </span>
        <a href="#" class="card-link"></a>
      </div>
    </div>
    <div class="card-dish-img">
      <div class="col-lg-6 col-sm-12 row-bg">
        <%#= image_tag @dish.picture.url(:large) %>
      </div>
    </div>
  </div>
</div>
 -->

app/views/dishes/update.html.erb
<h1>Dishes#update</h1>
<p>Find me in app/views/dishes/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YUMMMY</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>
  <body>
    <%= render 'shared/navbar1' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/destroy.html.erb
<h1>Orders#destroy</h1>
<p>Find me in app/views/orders/destroy.html.erb</p>

app/views/orders/edit.html.erb
<h1>Orders#edit</h1>
<p>Find me in app/views/orders/edit.html.erb</p>

app/views/orders/index.html.erb
<div class="container text-center">
  <div class="container-fluid">
  <div class="row">
    <div class="col-xs-offset-3 col-xs-6 ">
      <head>

  <title>Bootstrap Case</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1" >
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>

<h5 class="typo_tab_title">option 1</h5>
  <h1 class="typo_tab_title">Menus de la semaine </h1>
  <p class="typo_tab">(cuisiné dans l'appart de Boris)</p>
  <br>


  <ul class="nav nav-tabs">
    <!-- <li class="active"><a href="#home">Home</a></li> -->
    <li><a href="#menu1">Lundi</a></li>
    <li><a href="#menu2">Mardi</a></li>
    <li><a href="#menu3">Mercredi</a></li>
    <li><a href="#menu4">Jeudi</a></li>
    <li><a href="#menu5">Vendredi</a></li>
    <li><a href="#menu6">Samedi</a></li>
    <li><a href="#menu7">Dima</a></li>
  </ul>
</div>
</div>

  <div class="tab-content text-center">
    <div id="menu1" class="tab-pane fade in active typo_tab">
     <!--  <h3>HOME</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </div>
    <div id="menu1" class="tab-pane fade"> -->
      <h3>Menu Big Fanfan</h3>
      <p> Délicieux hamburger sain avec frites saupoudrées d’ail et relevées de paprika </p>
      <div class="col-md-2 col-md-offset-4">
  <%= image_tag "lucien.jpg", width:"300px", id: "logo" %>
</div>


    </div>
    <div id="menu2" class="tab-pane fade typo_tab">
      <h3>Menu Burrito</h3>
     <p>Tortilla de blé, riz coriandre/citron-vert, haricots pinto ou haricots noirs, viande (carnitas, barbacoa, poulet ou steak adobo/chipotle grillé), guacamole, salsa, fromage et crème.</p>
     <div class="col-md-2 col-md-offset-4">
  <%= image_tag "burritos.jpg", width:"300px", id: "logo" %>
</div>


    </div>
    <div id="menu3" class="tab-pane fade typo_tab">
      <h3>Menu Yummmy sushis</h3>
      <p>E6 Spring Saumon Avocat, 6 Maki Saumon, 6 Maki Salmon Roll, 6 California Saumon Avocat</p>
      <div class="col-md-2 col-md-offset-4">
  <%= image_tag "planet-maki.jpg", width:"300px", id: "logo" %>
</div>



    </div>
    <div id="menu4" class="tab-pane fade typo_tab">
      <h3>Menu Yummmy imperial</h3>
      <p>Nouilles chinoises (Nouilles roulées à la main)
Les nouilles chinoises (ou “nouilles roulées à la main”) se trouvent parmi les pâtes chinoises traditionnelles ou Nouilles sautées végétariennes
Nouilles sautées végétariennes, facile à apprendre mais délicieuses, cette nourriture est un symbole parmi les pâtes chinoises.</p>
<div class="col-md-2 col-md-offset-4">
  <%= image_tag "nouilles.jpg", width:"300px", id: "logo" %>
</div>



    </div>
    <div id="menu5" class="tab-pane fade typo_tab">
      <h3>Menu Yummmy sawdwich</h3>
      <p>Sandwich de qualité au fromage de chèvre et au miel dans un pain au céréales</p>
      <div class="col-md-2 col-md-offset-4">
        <%= image_tag "chèvre et miel2.jpg", width:"300px", id: "logo" %>
      </div>

      </div>


<script>
$(document).ready(function(){
    $(".nav-tabs a").click(function(){
        $(this).tab('show');
    });
});
</script>


</body>
<!-- <br>
<div class="col-md-2 col-md-offset-4">
  <%= image_tag "lucien.jpg", width:"300px", id: "logo" %>
</div>
 -->
<br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br>


<h3><%= link_to "Pré-commander", order_path(:id) %></h3>

app/views/orders/new.html.erb
<div class="container text-center">
  <div class="container-fluid">
  <div class="row">
    <div class="col-xs-offset-3 col-xs-6 ">
      <head>

  <title>Bootstrap Case</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1" >
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>

<h5 class="typo_tab_title">option 1</h5>
  <h1 class="typo_tab_title">Menus de la semaine </h1>
  <p class="typo_tab">(cuisiné dans l'appart de Boris)</p>
  <br>


  <ul class="nav nav-tabs">
    <!-- <li class="active"><a href="#home">Home</a></li> -->
    <li><a href="#menu1">Lundi</a></li>
    <li><a href="#menu2">Mardi</a></li>
    <li><a href="#menu3">Mercredi</a></li>
    <li><a href="#menu4">Jeudi</a></li>
    <li><a href="#menu5">Vendredi</a></li>
    <li><a href="#menu6">Samedi</a></li>
    <li><a href="#menu7">Dima</a></li>
  </ul>
</div>
</div>

  <div class="tab-content text-center">
    <div id="menu1" class="tab-pane fade in active typo_tab">
     <!--  <h3>HOME</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </div>
    <div id="menu1" class="tab-pane fade"> -->
      <h3>Menu Big Fanfan</h3>
      <p> Délicieux hamburger sain avec frites saupoudrées d’ail et relevées de paprika </p>
      <div class="col-md-2 col-md-offset-4">
  <%= image_tag "lucien.jpg", width:"300px", id: "logo" %>
</div>


    </div>
    <div id="menu2" class="tab-pane fade typo_tab">
      <h3>Menu Burrito</h3>
     <p>Tortilla de blé, riz coriandre/citron-vert, haricots pinto ou haricots noirs, viande (carnitas, barbacoa, poulet ou steak adobo/chipotle grillé), guacamole, salsa, fromage et crème.</p>
     <div class="col-md-2 col-md-offset-4">
  <%= image_tag "burritos.jpg", width:"300px", id: "logo" %>
</div>


    </div>
    <div id="menu3" class="tab-pane fade typo_tab">
      <h3>Menu Yummmy sushis</h3>
      <p>E6 Spring Saumon Avocat, 6 Maki Saumon, 6 Maki Salmon Roll, 6 California Saumon Avocat</p>
      <div class="col-md-2 col-md-offset-4">
  <%= image_tag "planet-maki.jpg", width:"300px", id: "logo" %>
</div>



    </div>
    <div id="menu4" class="tab-pane fade typo_tab">
      <h3>Menu Yummmy imperial</h3>
      <p>Nouilles chinoises (Nouilles roulées à la main)
Les nouilles chinoises (ou “nouilles roulées à la main”) se trouvent parmi les pâtes chinoises traditionnelles ou Nouilles sautées végétariennes
Nouilles sautées végétariennes, facile à apprendre mais délicieuses, cette nourriture est un symbole parmi les pâtes chinoises.</p>
<div class="col-md-2 col-md-offset-4">
  <%= image_tag "nouilles.jpg", width:"300px", id: "logo" %>
</div>



    </div>
    <div id="menu5" class="tab-pane fade typo_tab">
      <h3>Menu Yummmy sawdwich</h3>
      <p>Sandwich de qualité au fromage de chèvre et au miel dans un pain au céréales</p>
      <div class="col-md-2 col-md-offset-4">
        <%= image_tag "chèvre et miel2.jpg", width:"300px", id: "logo" %>
      </div>

      </div>


<script>
$(document).ready(function(){
    $(".nav-tabs a").click(function(){
        $(this).tab('show');
    });
});
</script>


</body>
<!-- <br>
<div class="col-md-2 col-md-offset-4">
  <%= image_tag "lucien.jpg", width:"300px", id: "logo" %>
</div>
 -->
<br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br>


<h3><%= link_to "Pré-commander", order_path(:id) %></h3>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

app/views/orders/update.html.erb
<h1>Orders#update</h1>
<p>Find me in app/views/orders/update.html.erb</p>

app/views/pages/home.html.erb
<h1 class="text-center">Aujourd'hui</h1>

<div class="container-fluid">
  <% @dishes.each do |dish| %>
  <div class="row">
    <div class="col-xs-offset-3 col-xs-6">
          <h3><%= raise dish.user.name%> vous propose : <%=dish.name%> pour <%=dish.price_per_portion%> € par portion</h3>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>



  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-offset-3 col-xs-6 ">
        <br>
        <span class="text-center" >
        <A HREF="/dishes#">Decouvrez l'ensemble des plats disponibles</A>
        </span>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar1.html.erb
<div class="container-fluid">

  <%= link_to chats_index_path do %>
    <%= image_tag "chat_logo3.jpg", width:"100px", id: "logo" %>
  <% end %>
  <div class="col-md-2"></div>
  <h1 class="yummmy col-xs-6 text-center typo_yummmy_home"><%= link_to "Yummmy", root_path %></h1>

        <% if user_signed_in? %>
          <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link hidden-xs" do %>
            <!--<div class="icon-badge-container">
              <i class="fa fa-envelope-o"></i>
              <div class="icon-badge icon-badge-blue">3</div>
            </div> -->
          <% end %>
          <div class="navbar-wagon-item">
            <div class="dropdown cta">

              <%= image_tag current_user.picture, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
<!--                 <li>
                  <%= link_to "#" do %>
                    <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
                  <% end %>
                </li>
                <li>
                  <%= link_to "#" do %>
                    <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
                  <% end %>
                </li> -->
                <li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        <% else %>
          <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link cta", id:'login'%>
        <% end %>

        <% if user_signed_in? %>
          <%= link_to t(".top_call_to_action", default: "Proposer un plat"), new_dish_path, class: "navbar-wagon-item navbar-wagon-button btn cta" %>
        <% else %>
           <%= link_to t(".top_call_to_action", default: "Proposer un plat"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link cta", id:'login'%>
        <% end %>


          </div>